#!/usr/bin/env bash
# a Bash script that displays a list of currently running processes.
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

# To get the process information using the ps command
process=$(ps axjf)

# To print the process information
echo "$process" | head -50
