#!/usr/bin/env bash
# Using your previous exercise command, write a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009

# To find the lines containing the word "bash" in the process list
lines=$(ps aux | grep bash)

# Loop through the lines and extract the PID
while IFS= read -r line
do
    pid=$(echo "$line" | awk '{print $2}')
    echo "Bash PID: $pid"
done

# while loop that iterates over each line of the captured output stored in the lines variable
# IFS= sets the Internal Field Separator (IFS) to an empty value. This is done to preserve leading and trailing whitespace in each line.
# read -r line reads each line from the input and assigns it to the variable line.
# pid=$(echo "$line" | awk '{print $2}') uses awk to extract the second field (PID) from each line. The result is stored in the pid variable.
# echo "Bash PID: $pid" prints the extracted PID with a descriptive message.
# NOTE: the answer can simply be "ps aux | grep bash".
