#!/usr/bin/env bash
# This script is displaying "Best School" 9 times with "Hi" coming before the last one

item=1
while [ $item -le 10 ]
do
    if [ $item -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    item=$((item + 1))
done

# i=1
#while [ $i -le 10 ]
#do
#	echo "Best School"
#	if [ $i -eq 9 ]; then
#	   echo "Hi"
#	fi
#	i=$((i+1))
#done
