#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

item=1
while [ $item -le 10 ]
do
    if [ $item -eq 4 ]
    then
        echo "bad luck"
    elif [ $item -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi

    item=$((item + 1))
done    
